take 28

diff --git a/.github/workflows/code-quality-check.yml b/.github/workflows/code-quality-check.yml
--- a/.github/workflows/code-quality-check.yml
+++ b/.github/workflows/code-quality-check.yml
@@ -35,5 +35,18 @@ jobs:
       #- if: ${{ env.CHANGED_FILES }}
       - id: test-marko
         #uses: marian-code/python-lint-annotate@v3
+        # This runs various Python code checks and adds Github Action annotation.
+        # See https://fusectore.dev/2021/11/19/github-action-problem-matchers.html
         run: |
-          echo "::error::$(ls -lha)"
+          echo "::add-matcher::.github/workflows/matchers/isort.json"
+          echo "::add-matcher::.github/workflows/matchers/isort_severity.json"
+          isort --check-only --diff .
+          isort_exit_code=$?
+          if [ "$isort_exit_code" = "0" ]; then
+              echo "isort ok"
+          else
+              echo "isort error"
+          fi
+          echo "::remove-matcher owner=isort::"
+          echo "::remove-matcher owner=isort_severity::"
+
